#!/bin/bash -e

# Idempotent: only sets a default if the param is currently unset (or empty
# string). Called by install (first install) and post-refresh (every snap
# refresh) so that new parameters introduced in a later snap revision get their
# defaults applied without clobbering user-modified values from earlier ones.

source "$SNAP/usr/bin/utils.sh"

set_default_if_unset() {
    local key="$1"
    local value="$2"
    local current
    current="$(snapctl get "$key" 2>/dev/null || true)"
    if [ -z "$current" ] || [ "$current" = "''" ]; then
        snapctl set "${key}=${value}"
        log "Applied default ${key}=${value} (was unset)"
    fi
}

# driver.model deliberately has NO default — the launcher refuses to start
# until the operator picks one (existing installs get their old
# driver.camera-model value migrated by the configure hook).
#
# driver.ip deliberately has NO default — PoE is the exception, not the norm;
# unset means USB.
#
# driver.depth/resolution/fps/imu/ir get concrete defaults below for a clean,
# predictable `snap get` on a fresh install (see CLAUDE.md "camera-params:
# autogenerated vs custom"). This is safe even for a host still pointed at an
# old hand-authored camera-params file (oak-d-pro, or anything not literally
# "autogenerated") — generate_camera_params.sh (called from `configure`) only
# ever touches camera-params-autogenerated.yaml; a custom-named file is fully
# hands-off, so these defaults never reach it.
set_default_if_unset driver.name oak
set_default_if_unset driver.camera-params autogenerated
set_default_if_unset driver.ffmpeg-params default
set_default_if_unset driver.startup-delay 30
set_default_if_unset driver.depth false
set_default_if_unset driver.pointcloud false
set_default_if_unset driver.resolution 720P
set_default_if_unset driver.fps 30
set_default_if_unset driver.imu false
set_default_if_unset driver.ir false
set_default_if_unset driver.rectify-rgb true
set_default_if_unset driver.bitrate 3400000
