#!/bin/bash -e

# Generates camera-params-autogenerated.yaml from the current driver.* snap
# config. Run by the configure hook whenever driver.camera-params=autogenerated
# (the default) — this is the ONE place driver.depth/resolution/fps/imu/ir/ip/bitrate
# turn into the depthai_ros_driver YAML that depthai.launch.py loads verbatim.
#
# Switching driver.camera-params to any other value stops this script from
# running at all (see snap/hooks/configure) — that file becomes fully
# hands-off, and depth/resolution/fps/imu/ir/ip/bitrate no longer have any effect.
# See CLAUDE.md "camera-params: autogenerated vs custom".

source "$SNAP/usr/bin/utils.sh"

NAME="$(snapctl get driver.name)"; : "${NAME:=oak}"
DEPTH="$(snapctl get driver.depth)"
RESOLUTION="$(snapctl get driver.resolution)"; : "${RESOLUTION:=720P}"
FPS="$(snapctl get driver.fps)"; : "${FPS:=30}"
IMU="$(snapctl get driver.imu)"
IR="$(snapctl get driver.ir)"
IP="$(snapctl get driver.ip)"
BITRATE="$(snapctl get driver.bitrate)"; : "${BITRATE:=3400000}"

# rgb.i_fps wants a float literal ("30.0"); i_low_bandwidth_frame_freq wants an
# int ("30") — depthai_ros_driver rejects a float there. The *.*) branch is
# unreachable today (configure's validate_number only accepts an integer for
# driver.fps) — kept defensively in case that constraint ever loosens.
case "$FPS" in
  *.*) FPS_FLOAT="$FPS"; FPS_INT="${FPS%%.*}" ;;
  *)   FPS_FLOAT="${FPS}.0"; FPS_INT="$FPS" ;;
esac

if [ "$DEPTH" = "true" ]; then
  PIPELINE_TYPE="husarion_depthai::pipeline_gen::RGBDDual"
else
  PIPELINE_TYPE="husarion_depthai::pipeline_gen::RGBDual"
fi

OUT="${SNAP_DATA}/camera-params-autogenerated.yaml"
{
  echo "---"
  echo "# GENERATED by generate_camera_params.sh from driver.* — hand edits are"
  echo "# overwritten on the next snap set. To customize freely: copy this file"
  echo "# under a new name and 'snap set husarion-depthai driver.camera-params=<name>'"
  echo "# (README \"Camera config\") — that stops this generation entirely."
  echo "/**:"
  echo "  ros__parameters:"
  # Suppresses the raw stream's image_transport republisher — else it collides
  # with the on-chip FFMPEGPacket on the same .../ffmpeg topic name (see
  # ros/husarion_depthai_pipeline).
  echo "    ${NAME}.rgb.image_raw.enable_pub_plugins: ['image_transport/raw']"
  if [ "$DEPTH" = "true" ]; then
    # Also allow lazy SOFTWARE depth compression (PNG, via compressed_depth_image_transport
    # — registered under the image_transport/ pluginlib namespace like all image_transport
    # publisher plugins, hence 'image_transport/compressedDepth' not the providing
    # package's own name; verified in ros-perception/image_transport_plugins' plugin XML).
    # Zero cost unless something actually subscribes to .../stereo/image_raw/compressedDepth.
    # Deliberately NOT 'image_transport/compressed' or 'theora' here — those assume 8-bit
    # color and mishandle 16-bit metric depth.
    echo "    ${NAME}.stereo.image_raw.enable_pub_plugins: ['image_transport/raw', 'image_transport/compressedDepth']"
  fi
  echo "    camera:"
  echo "      i_pipeline_type: '${PIPELINE_TYPE}'"
  if [ "$IR" = "true" ]; then echo "      i_enable_ir: true"; else echo "      i_enable_ir: false"; fi
  echo "      i_nn_type: none"
  echo "      i_restart_on_diagnostics_error: true"
  if [ -n "$IP" ]; then
    echo "      i_ip: '${IP}'"
  fi
  # camera.i_enable_imu is a dead param (never read — verified against
  # depthai-ros v2.12.2-jazzy's pipeline_generator.cpp); the IMU node is
  # actually gated by pipeline_gen.i_enable_imu, default true.
  echo "    pipeline_gen:"
  if [ "$IMU" = "true" ]; then echo "      i_enable_imu: true"; else echo "      i_enable_imu: false"; fi
  echo "    rgb:"
  echo "      i_enable_lazy_publisher: false"
  echo "      i_fps: ${FPS_FLOAT}"
  echo "      i_resolution: '${RESOLUTION}'"
  echo "      i_max_q_size: 4"
  # H264_BASELINE (no B-frames): the telepresence consumer (cockpit) decodes
  # this on-chip stream in the browser via WebCodecs, same 1-in-1-out
  # requirement as the software libx264 leg in ffmpeg-params-default.yaml.
  echo "      i_low_bandwidth_profile: 0"
  echo "      i_low_bandwidth_bitrate: ${BITRATE}"
  echo "      i_low_bandwidth_frame_freq: ${FPS_INT}"
  if [ "$DEPTH" = "true" ]; then
    echo "    stereo:"
    echo "      i_align_depth: true"
    echo "      i_lr_check: true"
    # RGBDDual's on-chip disparity-H.264 leg needs 8-bit input — the OAK
    # VideoEncoder rejects 16-bit subpixel disparity (ros/husarion_depthai_pipeline).
    echo "      i_subpixel: false"
  fi
} > "$OUT"

log "generate_camera_params: wrote ${OUT} (pipeline=${PIPELINE_TYPE} resolution=${RESOLUTION} fps=${FPS} bitrate=${BITRATE})"
