name: Build snap
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: jazzy

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Render snapcraft.yaml
        run: |
          pip install jinja2
          export ROS_DISTRO=${{ matrix.ros_distro }}
          ./render_template.py ./snapcraft_template.yaml.jinja2 snap/snapcraft.yaml

      - name: Build snap
        uses: snapcore/action-build@v1
        with:
          snapcraft-channel: latest/edge
        id: build-snap
        env:
          SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: 1

      - name: Make sure the snap is installable
        run: |
          sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}
