#!/bin/sh -e

# now we can start the service
# if snapctl services ${SNAP_NAME}.daemon | grep -q inactive; then
#   snapctl start --enable ${SNAP_NAME}.daemon 2>&1 || true
# fi

logger -t ${SNAP_NAME} "Plug 'ros-humble-ros-base' connected"