#!/bin/bash -e

# Define a function to log and echo messages
source $SNAP/usr/bin/utils.sh

$SNAP/usr/bin/install_hook_ros.sh

snapctl set driver.name=oak
snapctl set driver.parent-frame=camera_mount_link
snapctl set driver.camera-model=OAK-D
snapctl set driver.cam-pos-x=0.0
snapctl set driver.cam-pos-y=0.0
snapctl set driver.cam-pos-z=0.0
snapctl set driver.cam-roll=0.0
snapctl set driver.cam-pitch=0.0
snapctl set driver.cam-yaw=0.0
snapctl set driver.camera-params=default
snapctl set driver.ffmpeg-params=default
snapctl set driver.startup-delay=10

if ! snapctl is-connected raw-usb; then
  log "Plug 'raw-usb' isn't connected, please run:"
  log "sudo snap connect ${SNAP_NAME}:raw-usb"
fi

# copy params
cp -r ${SNAP}/usr/share/${SNAP_NAME}/config/*.yaml ${SNAP_COMMON}/

cp -r "$SNAP/usr/bin/post_install.sh" "${SNAP_COMMON}/"

# # # copy meshes to shared folder
# log "copy meshes to '${SNAP_COMMON}/ros2_ws/'"
# mkdir -p ${SNAP_COMMON}/ros2_ws
# cp -r $SNAP/opt/ros/humble/share/depthai_descriptions ${SNAP_COMMON}/ros2_ws/depthai_descriptions
