#!/bin/sh -e

# Define a function to log messages
log() {
  local message="$1"
  # Log the message with logger
  logger -t "${SNAP_NAME}" "install hook: $message"
}

$SNAP/usr/bin/install_hook_ros.sh

snapctl set driver.name=oak
snapctl set driver.parent-frame=oak-d-base-frame
snapctl set driver.camera-model=OAK-D
snapctl set driver.cam-pos-x=0.0
snapctl set driver.cam-pos-y=0.0
snapctl set driver.cam-pos-z=0.0
snapctl set driver.cam-roll=0.0
snapctl set driver.cam-pitch=0.0
snapctl set driver.cam-yaw=0.0
snapctl set driver.params-file=$SNAP_COMMON/depthai_params.yaml
snapctl set driver.ffmpeg-image-transport.encoding=libx264
snapctl set driver.ffmpeg-image-transport.preset=ultrafast
snapctl set driver.ffmpeg-image-transport.tune=zerolatency
snapctl set driver.namespace!
snapctl set driver.device-namespace!

if ! snapctl is-connected raw-usb; then
  log "Plug 'raw-usb' isn't connected, please run:"
  log "sudo snap connect ${SNAP_NAME}:raw-usb"
fi

# copy joy params
cp -r $SNAP/usr/share/husarion-depthai/config/*.yaml ${SNAP_COMMON}/

# # copy meshes to shared folder
log "copy meshes to '${SNAP_COMMON}/ros2_ws/'"
mkdir -p ${SNAP_COMMON}/ros2_ws
cp -r $SNAP/opt/ros/humble/share/depthai_descriptions ${SNAP_COMMON}/ros2_ws/depthai_descriptions
